default: true

MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  tables: false

MD003:
  style: "atx"

MD033: false

MD041: true

MD040: true

MD025:
  front_matter_title: ""
