name: Docs Validate

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**/*.md'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**/*.md'

jobs:
  docs-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Setup Vale
        uses: errata-ai/vale-action@v2
        with:
          files: docs

      - name: Install markdown-link-check (optional)
        run: npm install -g markdown-link-check

      - name: Run docs validation
        run: make docs-validate

      - name: Summarize results
        if: always()
        run: |
          echo "## Docs Validation" >> "$GITHUB_STEP_SUMMARY"
          if [ "${{ job.status }}" = 'success' ]; then
            echo "All documentation checks passed." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "Documentation checks failed. See logs for details." >> "$GITHUB_STEP_SUMMARY"
